
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: charite_db
      POSTGRES_USER: charite_user
      POSTGRES_PASSWORD: charite_pass
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: charite-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres