spring.application.name=gestionCharite

spring.datasource.url=jdbc:postgresql://localhost:5432/charite_db
spring.datasource.username=charite_user
spring.datasource.password=charite_pass

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

